# Generated by Django 2.1.1 on 2018-10-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtendedAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('FileName', models.CharField(default=None, max_length=100)),
                ('URL', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='addperson',
            name='AddID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddField.Person'),
        ),
    ]
